### PR TITLE
feat(index): Return error status code on error (standard Http check)

### LINKED ISSUE #21: Revert to Pingdom Standard Http Check
**Is your feature request related to a problem? Please describe.**
The Pingdom Http Custom checks that we’re currently using are IMO useless for Root Cause Analysis & Troubleshouting . Only the Status and the Response Time of the XML response are processed/reported on Pingdom.com. The additional information/context that `helix-pingdom-status` provides (such as `<activation>`  and `<error>`) is ignored by Pingdom and doesn’t  show up on _Get Content_. Neither do the received headers. As a consequence you’ll have to manually dig through the activations to find the action response.

**Describe the solution you'd like**
Reverting back to  standard Http check support all information (status code, response body, response headers) is available on  _Get Content_. For simplicity's sake I suggest we keep the current XML response format but return an appropriate Http error status in case of an error (instead of unconditional `200` as mandated by the custom Http checks). Returning a status != 200 will trigger an incident. We'll have to reconfigure the Pingdom checks.

### PR DESCRIPTION
**Pull request by stefan-guggisberg**
BREAKING CHANGE: Returns error Http status on error (Standard Http check) instead of always 200
(Custom Http check)

fix #21

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

**Comment by stefan-guggisberg** [comment]
@tripodsan 
> what about setting the statusCode based on the request url?
eg:
`_status_check/ping.xml` -> 500
`_status_check/pingdom.xml` -> 200

I don't agree. It's IMO non-intuitive and I don't see the point in the 2nd variant which would only make sense for Pingdom Custom Http checks. The whole point of this issue/PR is that we don't want to use Custom checks as they've proven to be useless for our case (Triggering incidents & provide information for RCA/troubleshooting).

**Comment by tripodsan** [comment]
> The whole point of this issue/PR is that we don't want to use Custom checks as they've proven to be useless for our case (Triggering incidents & provide information for RCA/troubleshooting).

I'm currently in contact with pingdom-support, and try to explain our problem... I just don't want to revert to the previous state, if they fix their ui.

**Comment by stefan-guggisberg** [comment]
> I'm currently in contact with pingdom-support, and try to explain our problem... I just don't want to revert to the previous state, if they fix their ui.

@tripodsan I don't get it. You're still insisting on your proposal (2 url's with different behaviour)?  Even if they do fix their UI anytime soon (I doubt it since it's likely not just an UI issue) it doesn't buy us anything. Custom checks don't have any advantage over standard UPTME checks for our use case (monitoring and troubleshooting/RCA).

The current situation with our useless Custom checks makes troubleshooting incidents really hard/impossible. If we do merge this PR we can change all our current Pingdom Custom checks to standard UPTIME checks and we're good. We won't have to revert to the previous state even if they would fix their Custom checks.

@trieloff WDYT?

**Comment by stefan-guggisberg** [comment]
If we return 200 we can’t use it for the standard UPTIME checks as
suggested by Pingdom. I don’t see the point in supporting  something in our
Pingdom specific repo that we don’t use.

If you insist on supporting two separate url’s with different behavior
please commit your suggested changes (including documentation and
explanation why we need it) to the branch.

**Comment by tripodsan** [comment]
> please commit your suggested changes (including documentation and explanation why we need it) to the branch.

this is not possible, since this PR is based on a fork ;-)

**Pull request merged**
